### ISSUE TITLE
Make "Advance clock" command support rolling instead of just advancing

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#220]
A core mechanic of clocks is that you determine how "likely" it is for the clock to advance, and you roll an oracle for it. Let's integrate this into the "Advance a clock" command.

**Comment by cwegrzyn** [comment]
Thinking about the UX here, would you imagine something like this @zkat ?

- When you create a clock, you can optionally associated a probability of advancement with it.
- When you "advance a clock", if the clock has a probability, we would give you a prompt choosing between "unconditionally advance" or "roll to advance (likelihood X)"
- If you roll to advance, we roll the likelihood oracle, record an oracle mechanics node corresponding to that, and then either advance the clock (recording a mechanics node for that) or not.

**Comment by zkat** [comment]
I really like this ux!

**Comment by cwegrzyn** [comment]
Oh, hmm, but it occurs to me that you might want different odds based on, e.g., how long it has been narratively since you last advanced or some other narrative reason.

I don't think we want two separate commands (one for unconditional tick and one for "roll for tick"), because that's kinda annoying for people who rely on the toolbar. (Or just if you forget that it is a separate command)

So maybe "advance a clock" always prompts you for the odds (where one of the options is "unconditional/advance without rolling"). When you create a clock, you specify the "default odds", and we always pre-select that, so you can skip through that page with just an enter if you typically make the same roll.
