### ISSUE TITLE
too many notifications when typing out new Homebrew directory

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#293]
If you try to type the name of a new Homebrew directory in settings, you'll get massive notification spam

**Comment by cwegrzyn** [comment]
Hrm. Not sure what to do about this. Options I can think of:

1. Don't give a notice if the folder is missing. Without doing option 2, this will still trigger a reload of the data on every keystroke though.
2. Only trigger a reload if we change from valid dir -> invalid dir or * -> valid dir. I'm not sure exactly how i'd do this though.
3. Maybe change the setting so that ONLY valid dirs are recorded (and therefore trigger updates). If you want to pick an invalid dir, well, don't do that: just turn off homebrew support entirely.
