### ISSUE TITLE
Add "make an action roll" command that rolls independently of a move

### ISSUE THREAD

**Issue by zkat** [iron-vault-plugin/iron-vault#326]

**Comment by cwegrzyn** [comment]
I think the idea for this was:

- If preceding adjacent move has no roll, add the roll to preceding move. (This is the "I decided to roll on endure harm" after not rolling.)
- Otherwise, just add a new top-level roll.

I think I'll also detect if the previous move has no roll at the start and then treat this explicitly as resuming that move (mainly, we would suggest the rollable stats/meters from that move). No great downside to this, since it is just a suggestion.
